spring:
  application:
    name: abixen-platform-business-intelligence-service

abixen:
  platform:
    adminSidebarItems:
      -
        title: Data Sources
        state: application.multiVisualization.modules.databaseDataSource.list
        orderIndex: 9
        id: 9
        iconClass: fa fa-database
    modules:
      -
        name: multi-visualization
        angularJsNameApplication: platformChartModule
        angularJsNameAdmin: TBD
        title: Multi Visualization
        description: This is a multi visualization module
        relativeInitUrl: /application/businessintelligence/abixen/multi-visualization/html/index.html
        staticResources:
          -
            relativeUrl: /application/businessintelligence/abixen/businessintelligence.min.js
            resourcePageLocation: BODY
            resourcePage: APPLICATION
            resourceType: JAVASCRIPT
          -
            relativeUrl: /application/businessintelligence/abixen/lib/d3.min.js
            resourcePageLocation: BODY
            resourcePage: APPLICATION
            resourceType: JAVASCRIPT
          -
            relativeUrl: /application/businessintelligence/abixen/lib/nv.d3.min.js
            resourcePageLocation: BODY
            resourcePage: APPLICATION
            resourceType: JAVASCRIPT
          -
            relativeUrl: /application/businessintelligence/abixen/lib/nv.d3.min.css
            resourcePageLocation: HEADER
            resourcePage: APPLICATION
            resourceType: CSS
          -
            relativeUrl: /application/businessintelligence/abixen/lib/angular-nvd3.min.js
            resourcePageLocation: BODY
            resourcePage: APPLICATION
            resourceType: JAVASCRIPT
          -
            relativeUrl: /admin/businessintelligence/abixen/lib/xlsx.full.min.js
            resourcePageLocation: BODY
            resourcePage: ADMIN
            resourceType: JAVASCRIPT
      -
        name: magic-number
        angularJsNameApplication: platformMagicNumberModule
        angularJsNameAdmin: TBD
        title: Magic Number
        description: This is a magic number module
        relativeInitUrl: /application/businessintelligence/abixen/magic-number/html/index.html
        staticResources:
          -
            relativeUrl: /application/businessintelligence/abixen/businessintelligence.min.js
            resourcePageLocation: BODY
            resourcePage: APPLICATION
            resourceType: JAVASCRIPT
      -
        name: kpi-chart
        angularJsNameApplication: platformKpiChartModule
        angularJsNameAdmin: TBD
        title: KPI Chart
        description: This is a KPI chart module
        relativeInitUrl: /application/businessintelligence/abixen/kpi-chart/html/index.html
        staticResources:
          -
            relativeUrl: /application/businessintelligence/abixen/businessintelligence.min.js
            resourcePageLocation: BODY
            resourcePage: APPLICATION
            resourceType: JAVASCRIPT
          -
            relativeUrl: /application/businessintelligence/abixen/lib/roundProgress.min.js
            resourcePageLocation: BODY
            resourcePage: APPLICATION
            resourceType: JAVASCRIPT