abixen:
  platform:
    core:
      version: @project.version@
spring:
  application:
    name: abixen-platform-core
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    generate-ddl: true
  cache:
    ehcache:
      config: classpath:ehcache.xml
liquibase:
  contexts: prod
  change-log: "classpath:liquibase/master-changelog.xml"